# Generated by Django 5.1.1 on 2025-02-05 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WildEye_Portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionrecord',
            name='image',
        ),
        migrations.RemoveField(
            model_name='detectionrecord',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='detectionrecord',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='detectionrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='detectionrecord',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detectionrecord',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='detections/photos/'),
        ),
        migrations.AddField(
            model_name='detectionrecord',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='detectionrecord',
            name='track_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
