from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('login/',views.login,name='user_login'),
    path('register/',views.register,name='user_register'),
    path('landing/',views.landing,name='landing'),
    path('verify_otp/',views.verify_otp, name='verify_otp'),
    path('resend_otp/', views.resend_otp, name='resend_otp'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('verify_reset_otp/', views.verify_reset_otp, name='verify_reset_otp'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('forgot_resend_otp/', views.forgot_resend_otp, name='forgot_resend_otp'),
    path('yolo/', views.yolo, name='yolo'),
    path("start_detection/", views.start_detection_view, name="start_detection"),
    path("stop_detection/", views.stop_detection_view, name="stop_detection"),
    path("get_detection_status/", views.get_detection_status, name="get_detection_status"),
    path('custom_admin/',views.custom_admin,name='custom_admin'),
    path('admin_cards/',views.admin_cards,name='admin_cards'),
    path('admin_table/',views.admin_table,name='admin_table'),
    path('user_list/', views.user_list, name='user_list'),
    path('message_cards/',views.message_cards,name='message_cards'),
    path('delete-record/<int:record_id>/', views.delete_record, name='delete_record'),
    path('delete-message/<int:record_id>/', views.delete_message, name='delete_message'),
    path('user_table/',views.user_table,name='user_table'),
    path('user_cards/',views.user_cards,name='user_cards'),
    path('about/',views.about,name='about'),
    path('services/',views.services,name='services'),
    path('team/',views.team,name='team'),
    path('contact/',views.contact,name='contact'),
    path('terms/',views.terms,name='terms'),
    path('change_Password/', views.change_password, name='change_password'),
    path('logout/', views.user_logout, name='logout'),
    path('admin_logout/', views.admin_logout, name='admin_logout'),
] 